
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoFinal
{
	public partial class BusquedaWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.DrawingArea drawingarea1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBoxEntry comboboxentry1;
		
		private global::Gtk.ComboBoxEntry comboboxentry2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoFinal.BusquedaWindow
			this.Name = "ProyectoFinal.BusquedaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("BusquedaWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoFinal.BusquedaWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Inicia");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 59;
			w1.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Termina");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w2.X = 48;
			w2.Y = 85;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.WidthRequest = 292;
			this.drawingarea1.HeightRequest = 336;
			this.drawingarea1.Name = "drawingarea1";
			this.fixed1.Add (this.drawingarea1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.drawingarea1]));
			w3.X = 24;
			w3.Y = 194;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Mapa");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w4.X = 45;
			w4.Y = 153;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry1.Name = "comboboxentry1";
			this.fixed1.Add (this.comboboxentry1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentry1]));
			w5.X = 113;
			w5.Y = 42;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry2.Name = "comboboxentry2";
			this.fixed1.Add (this.comboboxentry2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentry2]));
			w6.X = 112;
			w6.Y = 82;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 656;
			this.DefaultHeight = 572;
			this.Show ();
		}
	}
}
